### ISSUE TITLE
failed to generate bindings: failed to unmarshal micheline code: unexpected end of JSON input

### ISSUE THREAD

**Issue by gluonfield** [jeanschmitt/tzgen#1]
The example command in README works fine, however when I tried on the following contract command failed with error

`failed to generate bindings: failed to unmarshal micheline code: unexpected end of JSON input`

Steps to reproduce

`go run github.com/jeanschmitt/tzgen --name Hello --pkg contracts --address KT1BJC12dG17CVvPKJ1VYaNnaT5mzfnUTwXv -o ./issuer.go`

**Comment by jeanschmitt** [comment]
Hi,

The default endpoint was ghostnet, so your contract was not found. I changed this default to mainnet, to make it clearer.

Also added support for lambda types and non-flat storage types, so that your contract is generated correctly
